# Zyron AI - Services Configuration
# Version: 2.0.0
# Documentation: docs/SERVICES.md

version: "2.0"

services:
  backend:
    name: "Backend API"
    description: "FastAPI backend with Uvicorn"
    type: "process"
    command: ".venv/bin/uvicorn server:app --reload --port 8000"
    directory: "backend"
    port: 8000
    health_check:
      type: "http"
      url: "http://localhost:8000/health"
      timeout: 5
      retries: 3
      interval: 2
    depends_on: []
    env_file: ".env"
    environment:
      PYTHONPATH: "${PWD}"
      ENVIRONMENT: "${ENVIRONMENT:-development}"
    critical: true
    enabled: true
    startup_timeout: 60

  frontend:
    name: "Frontend Vite"
    description: "React + Vite development server"
    type: "process"
    command: "npm run dev"
    directory: "frontend"
    port: 5173
    health_check:
      type: "http"
      url: "http://localhost:${FRONTEND_PORT:-5173}"
      timeout: 10
      retries: 3
      interval: 3
    depends_on: []
    critical: false
    enabled: true
    startup_timeout: 60

  postgres:
    name: "PostgreSQL Database"
    description: "PostgreSQL 16 database server"
    type: "docker"
    image: "postgres:16-alpine"
    container_name: "zyron_postgres"
    port: 5432
    command: null
    environment:
      POSTGRES_DB: "${DB_NAME:-zyron_dev}"
      POSTGRES_USER: "${DB_USER:-zyron}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-dev_password_change_in_prod}"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    health_check:
      type: "command"
      command: "pg_isready -U ${DB_USER:-zyron}"
      timeout: 10
      retries: 10
      interval: 2
    depends_on: []
    critical: true
    enabled: true
    startup_timeout: 60

  redis:
    name: "Redis Cache"
    description: "Redis 7 for caching and queues"
    type: "docker"
    image: "redis:7-alpine"
    container_name: "zyron_redis"
    port: 6379
    command: "redis-server --appendonly yes"
    environment: {}
    volumes:
      - "./data/redis:/data"
    health_check:
      type: "command"
      command: "redis-cli ping"
      timeout: 5
      retries: 5
      interval: 1
    depends_on: []
    critical: false
    enabled: true
    startup_timeout: 30

  visual-brain:
    name: "Visual Brain Service"
    description: "ML-powered visual generation (Stub mode - Phase 3)"
    type: "process"
    command: "uvicorn visual_brain.server:app --port ${VISUAL_BRAIN_PORT:-8001} --workers 1"
    directory: "."
    port: 8001
    health_check:
      type: "http"
      url: "http://localhost:${VISUAL_BRAIN_PORT:-8001}/health"
      timeout: 5
      retries: 3
      interval: 2
    depends_on: [redis]
    environment:
      PYTHONPATH: "${PWD}"
      GPU_ENABLED: "false"
      MODEL_CACHE: "./models"
    gpu_required: true
    critical: false
    enabled: false
    startup_timeout: 60
    description_extended: "This is a stub. ML implementation coming in Phase 3."
