# Zyron AI - Base Configuration
# This is the foundation config, overridden by environment-specific files

project:
  name: "Zyron AI"
  version: "0.2.0"
  description: "AI-powered visual generation platform"

environment: "development"
debug: true

# Backend configuration
backend:
  port: 8000
  host: "127.0.0.1"
  log_level: "info"
  reload: true
  workers: 1
  timeout: 300
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "http://127.0.0.1:5173"
    - "http://127.0.0.1:3000"

# Frontend configuration
frontend:
  port: 5173
  host: "localhost"

# Database configuration
database:
  pool_size: 5
  pool_timeout: 30
  pool_recycle: 3600
  echo_sql: false
  max_overflow: 10

# Redis configuration
redis:
  max_connections: 10
  timeout: 30
  retry_on_timeout: true

# Visual Brain configuration
visual_brain:
  port: 8001
  host: "127.0.0.1"
  workers: 1
  gpu_required: false
  model_cache: "./models"

# Logging configuration
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "standard"
    file:
      class: "logging.FileHandler"
      level: "INFO"
      formatter: "standard"
      filename: "logs/app.log"
  root:
    level: "INFO"
    handlers: ["console", "file"]
