# Zyron AI - Development Configuration
# Use SQLite, minimal setup, hot reload enabled

environment: development
debug: true

backend:
  port: 8000
  reload: true
  workers: 1
  log_level: "debug"

database:
  type: "sqlite"
  path: "data/zyron_dev.db"
  echo_sql: false
  pool_size: 1

redis:
  enabled: false
  host: "localhost"
  port: 6379

visual_brain:
  enabled: false
  gpu: false
